const ATTENDANCE_STATUSES = Object.freeze({
  PRESENT: 'PRESENT',
  LATE: 'LATE',
  EARLY_LEAVE: 'EARLY_LEAVE',
  ABSENT: 'ABSENT',
  HALF_DAY: 'HALF_DAY',
  OVERTIME: 'OVERTIME',
  REMOTE_WORK: 'REMOTE_WORK',
  ON_LEAVE: 'ON_LEAVE',
  SICK_LEAVE: 'SICK_LEAVE',
});

module.exports = { ATTENDANCE_STATUSES };
