/** Reference catalog from Book2.xlsx — seeded on migrate; admin may add/remove via API. */

function dedupeItems(items) {
  const seen = new Set();
  const out = [];
  for (const raw of items) {
    const k = String(raw ?? '')
      .trim()
      .replace(/\s+/g, ' ')
      .toUpperCase();
    if (!k || seen.has(k)) continue;
    seen.add(k);
    out.push(k);
  }
  return out;
}

const PABRIK_CATALOG = [
  {
    code: '1',
    name: 'PAKERIN',
    items: [
      'PA1',
      'PA1B',
      'PA2',
      'PA2B',
      'PA3',
      'PA3B',
      'PBB',
      'PBBPB',
      'PBBPBBSH',
      'PBBPBM',
      'PBBSH',
      'PBK',
      'PBLD',
      'PBLDB',
      'PBM',
      'PBMB',
      'PBMLD',
      'PBPB',
      'PBPBB',
      'PBPBM',
      'PBPBMB',
      'PCUMKW2',
      'PDD',
      'PDP',
      'PDPB',
      'PD1',
      'PDTB',
      'PKPU',
      'PM',
      'PMB',
      'PMIX',
      'PMLDB',
      'PWD',
      'PWP',
      'PWPB',
      'PWT',
      'PWTB',
    ],
  },
  {
    code: '2',
    name: 'SUPARMA',
    items: [
      'SB',
      'SBB',
      'SCD',
      'SDP',
      'SG',
      'SH',
      'SHG1',
      'SHG2',
      'SHG3',
      'SIC',
      'SIP',
      'SKBK',
      'SKBR',
      'SKC',
      'SKPU',
      'SWPTC',
      'SWPTP',
    ],
  },
  {
    code: '3',
    name: 'MEGA SURYA ERATAMA - JASEM',
    items: [
      'JSB',
      'JSBO',
      'JSDP',
      'JSDPO',
      'JSDPT',
      'JSDTO',
      'JSG',
      'JSKPU',
      'JSKO',
      'JSONP',
      'JSOO',
      'JSSWLA',
      'JSSWLAO',
      'JSSWLC',
      'JSSWLCO',
    ],
  },
  {
    code: '4',
    name: 'STARPAPER',
    items: [
      'SPB',
      'SPBBP',
      'SPBK',
      'SPBPB',
      'SPMIX',
      'SPMIXNT',
      'SPMIXT',
    ],
  },
  {
    code: '5',
    name: 'BUANA MEGAH - BEJI',
    items: [
      'BB',
      'BBIR',
      'BBK',
      'BBS',
      'BCON',
      'BDPA',
      'BDPB',
      'BPPCON',
      'BIW',
      'BK',
      'BM',
      'BMAI',
      'BMS',
      'BSWL',
      'BSWLD',
      'BTBK',
    ],
  },
  {
    code: '6',
    name: 'ADIPRIMA SURAPRINTA - JAWAPOS',
    items: [
      'JPB',
      'JPDP',
      'JPDPP',
      'JPK',
      'JPKPUO',
      'JPOM',
      'JPONP',
      'JPONPA',
      'JPOO',
      'JPS',
      'JPSDG',
      'JPSM',
      'JPSS',
      'JPSWLA',
    ],
  },
  {
    code: '7',
    name: 'MEKABOX INTERNATIONAL',
    items: [
      'MIB',
      'MIBBP',
      'MIBCON',
      'MIBLP',
      'MIBPB',
    ],
  },
  {
    code: '8',
    name: 'SURABAYA MEKABOX',
    items: [
      'SMBB',
      'SMBBP',
      'SMBBPB',
      'SMBDP',
      'SMBM',
      'SMBPP',
      'SMBBLP',
    ],
  },
  {
    code: '9',
    name: 'EKAMAS',
    items: [
      'EKMBBP',
      'EKMBC',
      'EKMBNP',
      'EKMBOA',
      'EKMBP',
    ],
  },
  {
    code: '10',
    name: 'TJIWI KIMIA',
    items: [
      'TKBBP',
      'TKBCON',
      'TKBNPM',
      'TKBNPS',
      'TKBSPM',
      'TKBSPS',
      'TKSWLAM',
      'TKSWLAS',
    ],
  },
  {
    code: '11',
    name: 'SUNPAPER',
    items: [
      'SPSSA',
      'SPSSB',
      'SPSSC',
      'SPTA',
      'SPTB',
    ],
  },
  {
    code: '12',
    name: 'DAYASA',
    items: [
      'DAPD1',
      'DAPDPP',
      'DAPMXD',
      'DAPMXM',
      'DAPOCB',
      'DAPOCM',
      'DAPOCP',
      'DAPONP',
      'DAPONPC',
      'DAPSWLA',
      'DAPSWLAC',
      'DAPSWLAB',
      'DAPSWLBC',
    ],
  },
].map((row, index) => ({
  code: row.code,
  name: row.name,
  sort_order: index + 1,
  items: dedupeItems(row.items),
}));

module.exports = { PABRIK_CATALOG, dedupeItems };
